#!/usr/bin/env node

/**
 * build-codex.js — Generate .codex/AGENTS.md from AlataFlow skills + CLAUDE.md
 *
 * Reads all skills/\*\/\*\/skill.md files and the project conventions,
 * then produces a consolidated AGENTS.md suitable for Codex CLI.
 *
 * Usage: node scripts/build-codex.js [--output path]
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { join, dirname, basename, relative } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, '..');

function findSkills() {
  const skillsDir = join(ROOT, 'skills');
  const skills = [];
  if (!existsSync(skillsDir)) return skills;

  for (const category of readdirSync(skillsDir, { withFileTypes: true })) {
    if (!category.isDirectory()) continue;
    const catDir = join(skillsDir, category.name);
    for (const skill of readdirSync(catDir, { withFileTypes: true })) {
      if (!skill.isDirectory()) continue;
      const skillFile = join(catDir, skill.name, 'skill.md');
      if (existsSync(skillFile)) {
        skills.push({
          category: category.name,
          name: skill.name,
          path: relative(ROOT, skillFile),
          content: readFileSync(skillFile, 'utf8'),
        });
      }
    }
  }
  return skills;
}

function extractCommand(content) {
  const m = content.match(/`\/alata:([^`]+)`/);
  return m ? '/alata:' + m[1] : null;
}

function extractPurpose(content) {
  const m = content.match(/## Purpose\n(.+)/);
  return m ? m[1].trim() : '';
}

function buildCommandTable(skills) {
  const rows = skills
    .map(s => {
      const cmd = extractCommand(s.content);
      const purpose = extractPurpose(s.content);
      if (!cmd) return null;
      return `| \`${cmd}\` | ${s.category} | ${purpose} |`;
    })
    .filter(Boolean);

  return [
    '| Command | Category | Description |',
    '|---------|----------|-------------|',
    ...rows,
  ].join('\n');
}

function buildSkillSummaries(skills) {
  return skills.map(s => {
    const cmd = extractCommand(s.content) ?? s.name;
    const purpose = extractPurpose(s.content);
    const lines = s.content.split('\n');
    // Extract anti-patterns if present
    const antiIdx = lines.findIndex(l => /anti-pattern/i.test(l));
    let antiPatterns = '';
    if (antiIdx >= 0) {
      const antiLines = [];
      for (let i = antiIdx + 1; i < lines.length && !lines[i].startsWith('## '); i++) {
        if (lines[i].startsWith('- ')) antiLines.push(lines[i]);
      }
      if (antiLines.length > 0) antiPatterns = '\n' + antiLines.join('\n');
    }
    return `### ${s.category}/${s.name}\n**Command**: \`${cmd}\`\n**Purpose**: ${purpose}${antiPatterns}`;
  }).join('\n\n');
}

function readProjectConventions() {
  // Read CLAUDE.md for git conventions and workflow
  const claudeMd = join(ROOT, 'CLAUDE.md');
  if (!existsSync(claudeMd)) return '';
  const content = readFileSync(claudeMd, 'utf8');

  // Extract key sections
  const sections = [];

  // Git conventions
  const gitMatch = content.match(/## Git 规范[\s\S]*?(?=\n## |$)/);
  if (gitMatch) sections.push(gitMatch[0].trim());

  return sections.join('\n\n');
}

function readStaticHeader() {
  const staticFile = join(ROOT, '.codex', 'AGENTS.md');
  if (existsSync(staticFile)) {
    return readFileSync(staticFile, 'utf8');
  }
  return '';
}

function generate() {
  const skills = findSkills();
  const conventions = readProjectConventions();

  const now = new Date().toISOString().slice(0, 10);

  // Read the existing hand-crafted AGENTS.md as the base
  const existingContent = readStaticHeader();

  // Build the auto-generated appendix
  const appendix = `
---

## Auto-Generated Skill Index

> Generated by \`scripts/build-codex.js\` on ${now}
> Source: ${skills.length} skills from skills/

${buildCommandTable(skills)}

---

## Skill Details

${buildSkillSummaries(skills)}
`;

  return existingContent.trimEnd() + '\n' + appendix;
}

// Main
const args = process.argv.slice(2);
let outputPath = join(ROOT, '.codex', 'AGENTS.md');

const outputIdx = args.indexOf('--output');
if (outputIdx >= 0 && args[outputIdx + 1]) {
  outputPath = args[outputIdx + 1];
}

const content = generate();
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, 'utf8');

const skills = findSkills();
console.log('✅ Generated ' + outputPath);
console.log('   Skills indexed: ' + skills.length);
console.log('   Size: ' + (Buffer.byteLength(content, 'utf8') / 1024).toFixed(1) + ' KB');
